name: hobat
version: "0.1.0"
slug: hobat
description: Hobat - thread mesh dashboard and diagnostics toolkit
url: "https://github.com/jhawk42/hobat"
image: ghcr.io/jhawk42/hobat
arch:
  - aarch64
  - amd64
init: false
startup: application
boot: auto
host_network: true
docker_api: true
environment:
  TD_OTBR_CONTAINER_NAME: addon_core_openthread_border_router
webui: "http://[HOST]:[PORT:9165]/"
watchdog: "tcp://[HOST]:[PORT:9165]"