name: Hobat
version: "0.9.5"
slug: hobat
description: Thread mesh dashboard and diagnostics toolkit
url: "https://github.com/jhawk42/hobat"
image: ghcr.io/jhawk42/hobat-ha-app
arch:
  - aarch64
  - amd64
init: false
startup: application
boot: auto
host_network: true
docker_api: true
environment:
  TD_OTBR_CONTAINER_NAME: addon_core_openthread_border_router
options:
  ot_rest_listen_addr: 127.0.0.1
  ot_rest_listen_port: 8081
  ha_matter_ws_host: localhost
  ha_matter_ws_port: 5580
schema:
  ot_rest_listen_addr: str
  ot_rest_listen_port: port
  ha_matter_ws_host: str
  ha_matter_ws_port: port
webui: "http://[HOST]:[PORT:9165]/"
watchdog: "tcp://[HOST]:[PORT:9165]"