import asyncio
import dataclasses
import email.utils
import json
import mimetypes
import os
import argparse
import logging
import sys
import time
import uuid
from pathlib import Path
from typing import Sequence
from collections.abc import Callable

import aiohttp.web
import aiohttp_cors

from util_data import (
    create_checkpoint_filename,
    format_data_dir_log_message,
    resolve_data_dir_with_source,
)
from td_const import TD_DATA_DIR_ARG_HELP

TD_WEB_HOST_ADDR = ""
TD_WEB_HOST_PORT = 9165

# Default max-age for data files in seconds; can be overridden per-file in FILE_ACTION_MAP.
TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT_DEV = 3600  # 1 hour in seconds
TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT_OPS = 86400  # 1 day in seconds

TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT = 86400  # 1 day in seconds
TD_FILE_CACHE_MAX_AGE_ENV_NAME = "TD_FILE_CACHE_MAX_AGE"

# ---------------------------------------------------------------------------
# Mapping table and cache helpers
# ---------------------------------------------------------------------------


@dataclasses.dataclass
class FileAction:
    """Describes how to obtain (or verify) a data file and its cache policy."""

    max_age_s: int
    # "STATIC" means the file is managed externally; never regenerated by the server.
    # A list of strings is passed as CLI arguments to td_cli.py.
    action: "str | list[str]"
    action_cost_s: int
    # When True the action is always dispatched via 202 + polling regardless of
    # action_cost_s.  Use this for any action whose worst-case duration exceeds
    # the browser-safe synchronous limit (~30 s) but is under _LONG_COST_THRESHOLD_S.
    force_async: bool = False


def _build_file_action_map(default_max_age_s: int) -> dict[str, FileAction]:
    return {
        # System
        # Fetches extaddr to device_label mapping file.
        "td-static-extaddr-device-label.json": FileAction(
            max_age_s=default_max_age_s, action=["merge-extaddr","--merge-mdns-br"], action_cost_s=2
        ),

        # mdns
        # Fetches mDNS using zeroconf. Browse window is ~60 sec per service type.
        "td-mdns-scopes-thread.json": FileAction(
            # ~60 sec browse
            max_age_s=default_max_age_s, action=["mdns", "thread"], action_cost_s=60, force_async=True,
        ),
        "td-mdns-scopes-br.json": FileAction(
            # ~60 sec browse
            max_age_s=default_max_age_s, action=["mdns", "br"], action_cost_s=60, force_async=True
        ),
        "td-mdns-scopes-hap.json": FileAction(
            # ~60 sec browse
            max_age_s=default_max_age_s, action=["mdns", "hap"], action_cost_s=60, force_async=True
        ),
        "td-mdns-scopes-matter.json": FileAction(
            # ~60 sec browse
            max_age_s=default_max_age_s, action=["mdns", "matter"], action_cost_s=60, force_async=True
        ),

        # otbr-cli
        # Single ot-ctl commands — near-instant.
        "td-otbr-cli-thread-network-info.json": FileAction(
            max_age_s=default_max_age_s, action=["otbr-cli", "thread-network-info"], action_cost_s=2
        ),
        "td-otbr-cli-router-table.json": FileAction(
            max_age_s=default_max_age_s, action=["otbr-cli", "router-table"], action_cost_s=2
        ),
        # meshdiag topology — single command, a few seconds.
        "td-otbr-cli-meshdiag-topology.json": FileAction(
            max_age_s=default_max_age_s, action=["otbr-cli", "meshdiag", "topology"], action_cost_s=6
        ),
        # Per-router meshdiag commands — ~1–2 s each router; 90 s for ~50-router network.
        # force_async=True: 90 s exceeds the browser-safe synchronous limit (~30 s).
        "td-otbr-cli-meshdiag-router-childip6.json": FileAction(
            max_age_s=default_max_age_s,
            action=["otbr-cli", "meshdiag", "childip6"],
            action_cost_s=90,
            force_async=True,
        ),
        "td-otbr-cli-meshdiag-router-childtables.json": FileAction(
            max_age_s=default_max_age_s,
            action=["otbr-cli", "meshdiag", "childtable"],
            action_cost_s=90,  # ~1–2 s per router
            force_async=True,
        ),
        "td-otbr-cli-meshdiag-router-neighbortables.json": FileAction(
            max_age_s=default_max_age_s,
            action=["otbr-cli", "meshdiag", "routerneighbortable"],
            action_cost_s=90,  # ~1–2 s per router
            force_async=True,
        ),
        # networkdiag — TLV request per router with retries; up to ~10 min on large networks.
        "td-otbr-cli-networkdiag-fetch-all.json": FileAction(
            max_age_s=default_max_age_s,
            action=["otbr-cli", "networkdiag", "fetch-all"],
            action_cost_s=600,  # ~10 min for ~60 routers with timeout retries
            force_async=True,
        ),
        # networkdiag multicast-network — TLV request per router with retries; up to ~16 seconds on large networks.
        "td-otbr-cli-networkdiag-multicast-network.json": FileAction(
            max_age_s=default_max_age_s,
            action=["otbr-cli", "networkdiag", "multicast-network"],
            action_cost_s=16,  # ~16 seconds with timeout retries
            force_async=True,
        ),
        # networkdiag multicast-neighbors — TLV request per router with retries; up to ~16 seconds on large networks.
        "td-otbr-cli-networkdiag-multicast-neighbors.json": FileAction(
            max_age_s=default_max_age_s,
            action=["otbr-cli", "networkdiag", "multicast-neighbors"],
            action_cost_s=16,  # ~16 seconds with timeout retries
            force_async=True,
        ),

        # otbr-restapi
        # REST API downloads — single HTTP call, near-instant.
        "td-otbr-restapi-dataset-active.json": FileAction(
            max_age_s=default_max_age_s, action=["otbr-restapi", "download"], action_cost_s=2
        ),
        "td-otbr-restapi-devices.json": FileAction(
            max_age_s=default_max_age_s, action=["otbr-restapi", "download"], action_cost_s=2
        ),
        "td-otbr-restapi-diagnostics.json": FileAction(
            max_age_s=default_max_age_s, action=["otbr-restapi", "download"], action_cost_s=2
        ),
        "td-otbr-restapi-devices-list.json": FileAction(
            max_age_s=default_max_age_s, action=["otbr-restapi", "devices", "list"], action_cost_s=2
        ),
        "td-otbr-restapi-devices-fetch.json": FileAction(
            max_age_s=default_max_age_s,
            action=["otbr-restapi", "devices", "fetch"],
            action_cost_s=40,
            force_async=True,
        ),
        "td-otbr-restapi-diagnostics-list.json": FileAction(
            max_age_s=default_max_age_s, action=["otbr-restapi", "diagnostics", "list"], action_cost_s=2
        ),
        "td-otbr-restapi-actions-list.json": FileAction(
            max_age_s=default_max_age_s, action=["otbr-restapi", "actions", "list"], action_cost_s=2
        ),
        "td-otbr-restapi-mesh-diagnostics-fetch-all.json": FileAction(
            max_age_s=default_max_age_s,
            action=[
                "otbr-restapi", "mesh-diagnostics", "fetch-all",
                "--routers-only", "--items-only",
            ],
            action_cost_s=1200,
            force_async=True,
        ),
        "td-otbr-restapi-diagnostics-fetch-all.json": FileAction(
            max_age_s=default_max_age_s,
            action=["otbr-restapi", "diagnostics", "fetch-all", "--items-only"],
            action_cost_s=1200,
            force_async=True,
        ),

        # Eve App
        # Eve topology exports — externally managed static files.
        "Eve Thread Network Layout.evethreadlayout": FileAction(
            max_age_s=default_max_age_s, action="STATIC", action_cost_s=2
        ),
        "td-eve-topology.json": FileAction(
            max_age_s=default_max_age_s, action=["process-eve"], action_cost_s=2
        ),

        # Thread Tools app — externally managed static file.
        "diagnostics.json": FileAction(
            max_age_s=default_max_age_s, action="STATIC", action_cost_s=2
        ),

        # Pre-merged output — produced by merge_dataset; treated as static here.
        "td-merged-topology-all.json": FileAction(
            max_age_s=default_max_age_s, action=["merge-dataset"], action_cost_s=2
        ),
    }


FILE_ACTION_MAP: dict[str, FileAction] = _build_file_action_map(
    TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT
)


# Normalised lowercase lookup table built once at import time so that
# get_file_action() is O(1) instead of O(n) for every request.
_FILE_ACTION_MAP_LOWER: dict[str, FileAction] = {
    k.lower(): v for k, v in FILE_ACTION_MAP.items()
}


# FileAction used for checkpoint partial files served via /api/data/{checkpoint_filename}.
# max_age_s=0: clients must always re-fetch; checkpoints are transient and change frequently.
# action="STATIC": serve file if present, 404 if absent; never trigger a regen subprocess.
_CHECKPOINT_FILE_ACTION = FileAction(max_age_s=0, action="STATIC", action_cost_s=0)


def _build_checkpoint_filename_set(file_action_map: dict[str, FileAction]) -> set[str]:
    """Return lowercase checkpoint filenames for every dynamic entry in file_action_map."""
    return {
        create_checkpoint_filename(filename).lower()
        for filename, fa in file_action_map.items()
        if fa.action != "STATIC"
    }


# Set of lowercase checkpoint filenames (e.g. 'td-otbr-cli-networkdiag-fetch-all.partial.json').
# Used by _resolve_and_validate for O(1) checkpoint acceptance without a FILE_ACTION_MAP entry.
_CHECKPOINT_FILENAMES: set[str] = _build_checkpoint_filename_set(FILE_ACTION_MAP)


def _set_default_file_cache_max_age(max_age_s: int) -> None:
    """Rebuild FILE_ACTION_MAP and derived lookup tables with a new default."""
    global FILE_ACTION_MAP, _FILE_ACTION_MAP_LOWER, _CHECKPOINT_FILENAMES
    FILE_ACTION_MAP = _build_file_action_map(max_age_s)
    _FILE_ACTION_MAP_LOWER = {k.lower(): v for k, v in FILE_ACTION_MAP.items()}
    _CHECKPOINT_FILENAMES = _build_checkpoint_filename_set(FILE_ACTION_MAP)


def get_file_action(filename: str) -> FileAction | None:
    """Case-insensitive O(1) lookup in FILE_ACTION_MAP.

    Returns the matching FileAction, or None if the filename is unknown.
    """
    return _FILE_ACTION_MAP_LOWER.get(filename.lower())


def is_file_fresh(file_path: Path, max_age_s: int) -> bool:
    """Return True if *file_path* exists and its mtime is within *max_age_s* seconds."""
    try:
        mtime = file_path.stat().st_mtime
    except FileNotFoundError:
        return False
    return (time.time() - mtime) < max_age_s


def parse_request_cache_control(header_value: str | None) -> dict:
    """Parse a Cache-Control request header string into a dict.

    Examples::

        parse_request_cache_control("no-cache")
        # -> {"no-cache": True}

        parse_request_cache_control("max-age=600, no-store")
        # -> {"max-age": 600, "no-store": True}

        parse_request_cache_control(None)
        # -> {}
    """
    if not header_value:
        return {}
    result: dict = {}
    for directive in header_value.split(","):
        directive = directive.strip()
        if "=" in directive:
            name, _, value = directive.partition("=")
            name = name.strip().lower()
            value = value.strip()
            try:
                result[name] = int(value)
            except ValueError:
                result[name] = value
        else:
            result[directive.lower()] = True
    return result


def build_cache_response_headers(max_age_s: int, file_mtime: float) -> dict[str, str]:
    """Return HTTP response headers for cache control.

    Returns a dict with ``Cache-Control`` and ``Last-Modified`` headers.
    ``Last-Modified`` reflects the file's actual modification time so that
    conditional GET (``If-Modified-Since``) works correctly.
    """
    last_modified = email.utils.formatdate(file_mtime, usegmt=True)
    return {
        "Cache-Control": f"no-cache, max-age={max_age_s}",
        "Last-Modified": last_modified,
    }


# ---------------------------------------------------------------------------
# End
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# aiohttp async server
# ---------------------------------------------------------------------------

# Ensure .mjs and other types are served with the right Content-Type on
# minimal container images where the OS mime database may be absent.
mimetypes.add_type("application/javascript", ".js")
mimetypes.add_type("application/javascript", ".mjs")
mimetypes.add_type("application/json", ".json")
mimetypes.add_type("text/css", ".css")
mimetypes.add_type("text/html", ".html")

# Keyed by *filename*; value is the asyncio.Task running run_td_cli for that file.
# Serves two purposes for the short-cost synchronous path:
#   1. Deduplication key — detect whether this exact file is already being generated.
#   2. Awaitable handle — late-arriving requests for the same file can join (await)
#      the in-flight task instead of spawning a second subprocess.
# Note: source-level serialization (preventing two different files of the same source
# from running concurrently) is handled separately via _source_locks / _get_source_lock.
_active_processes: dict[str, "asyncio.Task[int]"] = {}

# Keyed by source name (action[0], e.g. "otbr-cli", "mdns", "otbr-restapi").
# Each lock serializes all td_cli subprocesses for that source so that only one
# runs at a time, preventing hardware/socket conflicts in the underlying CLI layer.
# In a long-lived server with many unique source keys this dict could grow
# unbounded. If that becomes a concern, add periodic cleanup (e.g. evict locks
# that are not locked and have not been used recently).
_source_locks: dict[str, asyncio.Lock] = {}


def _get_source_lock(source: str) -> asyncio.Lock:
    """Return the asyncio.Lock for *source*, creating it lazily if absent."""
    if source not in _source_locks:
        _source_locks[source] = asyncio.Lock()
    return _source_locks[source]


# async job tracking
_LONG_COST_THRESHOLD_S = 300  # actions with cost > this get 202 + polling

# Phase 1 contract: explicit job status model used by polling/cancel APIs.
JOB_STATUS_RUNNING = "running"
JOB_STATUS_CANCELLING = "cancelling"
JOB_STATUS_CANCELLED = "cancelled"
JOB_STATUS_DONE = "done"
JOB_STATUS_ERROR = "error"

_JOB_TERMINAL_STATUSES: set[str] = {
    JOB_STATUS_CANCELLED,
    JOB_STATUS_DONE,
    JOB_STATUS_ERROR,
}

_JOB_CANCELLABLE_STATUSES: set[str] = {JOB_STATUS_RUNNING}


@dataclasses.dataclass
class JobStatus:
    job_id: str
    filename: str
    # "running" | "cancelling" | "cancelled" | "done" | "error"
    status: str
    detail: str = ""
    created_at: float = dataclasses.field(default_factory=time.time)


@dataclasses.dataclass
class JobRuntime:
    """In-memory runtime handles for a long-cost job."""

    job_id: str
    filename: str
    source: str
    task: "asyncio.Task[None]"
    process: "asyncio.subprocess.Process | None" = None


def _is_terminal_job_status(status: str) -> bool:
    """Return True when *status* is a terminal job state."""
    return status in _JOB_TERMINAL_STATUSES


def _is_cancellable_job_status(status: str) -> bool:
    """Return True when *status* is currently cancellable."""
    return status in _JOB_CANCELLABLE_STATUSES


def _build_job_poll_body(job: JobStatus) -> dict[str, object]:
    """Build JSON payload for GET /api/job/{job_id} based on status."""
    if job.status == JOB_STATUS_RUNNING:
        return {"status": JOB_STATUS_RUNNING}
    if job.status == JOB_STATUS_CANCELLING:
        return {"status": JOB_STATUS_CANCELLING}
    if job.status == JOB_STATUS_CANCELLED:
        return {"status": JOB_STATUS_CANCELLED, "detail": job.detail}
    if job.status == JOB_STATUS_DONE:
        return {"status": JOB_STATUS_DONE, "filename": job.filename}
    # Unknown statuses are surfaced as error payloads to keep polling robust.
    if job.status != JOB_STATUS_ERROR:
        return {
            "status": JOB_STATUS_ERROR,
            "detail": f"Unknown job status: {job.status}",
        }
    return {"status": JOB_STATUS_ERROR, "detail": job.detail}


def _to_epoch_ms(ts: float) -> int:
    """Convert a POSIX timestamp in seconds to integer epoch milliseconds."""
    return int(ts * 1000)


def _build_checkpoint_poll_metadata(filename: str, data_dir: Path) -> dict[str, object]:
    """Build additive checkpoint metadata for a running long-cost job.

    Metadata fields are omitted when inputs are unavailable. The caller is
    expected to attach this only for non-terminal in-progress polling states.
    """
    checkpoint_filename = create_checkpoint_filename(filename)
    checkpoint_path = data_dir / checkpoint_filename
    final_path = data_dir / filename

    metadata: dict[str, object] = {
        "checkpoint_filename": checkpoint_filename,
        "final_last_modified_if_exists": None,
    }

    final_mtime: float | None = None
    checkpoint_mtime: float | None = None

    try:
        final_mtime = final_path.stat().st_mtime
        metadata["final_last_modified_if_exists"] = _to_epoch_ms(final_mtime)
    except FileNotFoundError:
        pass

    try:
        checkpoint_mtime = checkpoint_path.stat().st_mtime
    except FileNotFoundError:
        return metadata

    metadata["checkpoint_last_modified"] = _to_epoch_ms(checkpoint_mtime)
    metadata["checkpoint_is_newer_than_final"] = (
        final_mtime is None or checkpoint_mtime > final_mtime
    )
    return metadata


def _set_job_runtime_process(
    job_id: str,
    process: "asyncio.subprocess.Process | None",
) -> None:
    """Set or clear the active subprocess handle for *job_id*."""
    runtime = _job_runtime_registry.get(job_id)
    if runtime is not None:
        runtime.process = process


def _clear_job_runtime(job_id: str) -> None:
    """Drop runtime tracking for *job_id* and remove reverse task index."""
    runtime = _job_runtime_registry.pop(job_id, None)
    if runtime is not None:
        _job_id_by_task.pop(runtime.task, None)


# Registry of in-flight and recently-completed jobs.
_job_registry: dict[str, JobStatus] = {}

# Phase 2 runtime index: O(1) lookup of active job task/process by job_id.
_job_runtime_registry: dict[str, JobRuntime] = {}

# Reverse index used by done-callback to clean up job runtime state in O(1).
_job_id_by_task: dict["asyncio.Task[None]", str] = {}

# Anchor set that keeps references to fire-and-forget background Tasks so the
# garbage collector cannot collect them before they complete (CPython allows GC
# of Task objects that have no other referents).
_background_tasks: set["asyncio.Task[None]"] = set()

# Cleanup schedule for the job registry.
_JOB_TTL_S = 900       # evict completed/errored jobs after 15 minutes
_CLEANUP_INTERVAL_S = 60  # run eviction sweep every 60 seconds
_JOB_CANCEL_GRACE_DETAIL = "Cancellation requested by client."
_PROCESS_TERMINATE_GRACE_S = 2.0


def _on_background_task_done(task: "asyncio.Task[None]") -> None:
    """Done-callback: discard the task from the anchor set and log any exception."""
    _background_tasks.discard(task)

    job_id = _job_id_by_task.pop(task, None)
    if job_id is not None:
        _clear_job_runtime(job_id)

    if not task.cancelled():
        exc = task.exception()
        if exc is not None:
            logging.error(
                "Background job task raised an unhandled exception: %s",
                exc,
                exc_info=exc,
            )


async def _cleanup_job_registry_loop() -> None:
    """Periodically evict completed/errored jobs older than _JOB_TTL_S."""
    while True:
        await asyncio.sleep(_CLEANUP_INTERVAL_S)
        now = time.time()
        expired = [
            jid
            for jid, j in list(_job_registry.items())
            if _is_terminal_job_status(j.status) and (now - j.created_at) > _JOB_TTL_S
        ]
        for jid in expired:
            _job_registry.pop(jid, None)
            _clear_job_runtime(jid)
        if expired:
            logging.debug(
                "Evicted %d expired job(s) from registry", len(expired))


def _safe_filename(filename: str) -> bool:
    """Return True if *filename* contains no path-traversal characters."""
    return (
        bool(filename)
        and "/" not in filename
        and "\\" not in filename
        and ".." not in filename
        and "\x00" not in filename
    )


async def run_td_cli(
    action_args: list[str],
    data_dir: Path,
    *,
    timeout_s: float | None = None,
    on_process_started: "Callable[[asyncio.subprocess.Process], None] | None" = None,
    on_process_ended: "Callable[[], None] | None" = None,
) -> int:
    """Invoke td_cli.py as a subprocess and return its exit code.

    *timeout_s* is the hard wall-clock deadline for the subprocess.  When the
    deadline expires the process is killed and ``asyncio.TimeoutError`` is
    re-raised to the caller.  Pass ``None`` (the default) to disable the
    timeout.
    """
    td_cli_path = Path(__file__).parent / "td_cli.py"
    logging.debug("Spawning subprocess: %s %s %s", 
                  sys.executable,
                  td_cli_path, 
                  " ".join(action_args))
    process = await asyncio.create_subprocess_exec(
        sys.executable,
        str(td_cli_path),
        "--datadir", str(data_dir),  # must precede action_args so td_cli.py's
        *action_args,                # top-level parser captures it before subcommand delegation
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    if on_process_started is not None:
        on_process_started(process)
    _t0 = time.monotonic()
    try:
        if timeout_s is not None:
            stdout, stderr = await asyncio.wait_for(
                process.communicate(), timeout=timeout_s
            )
        else:
            stdout, stderr = await process.communicate()
    except asyncio.CancelledError:
        logging.info(
            "Subprocess cancelled; terminating process (args: %s)",
            " ".join(action_args),
        )
        try:
            if process.returncode is None:
                process.terminate()
                try:
                    logging.debug("Waiting up to %.1f s for subprocess to terminate gracefully", _PROCESS_TERMINATE_GRACE_S)
                    await asyncio.wait_for(
                        process.communicate(), timeout=_PROCESS_TERMINATE_GRACE_S
                    )
                except asyncio.TimeoutError:
                    logging.warning("Subprocess did not terminate gracefully; killing process")
                    process.kill()
                    await process.communicate()
        finally:
            raise
    except asyncio.TimeoutError:
        logging.warning(
            "Subprocess timed out after %.1f s (args: %s); killing process",
            timeout_s,
            f"{sys.executable} {td_cli_path} {' '.join(action_args)}",
            )
        process.kill()
        # reap the child to avoid zombie
        await process.communicate()  
        raise
    finally:
        if on_process_ended is not None:
            on_process_ended()
        logging.debug(
            "Subprocess elapsed %.3f s  %s %s %s",
            time.monotonic() - _t0,
            sys.executable,
            td_cli_path,
            " ".join(action_args)
        )
    if stdout:
        logging.info("td_cli stdout: %s", stdout.decode(errors="replace"))
    if stderr:
        logging.warning("td_cli stderr: %s", stderr.decode(errors="replace"))
    return process.returncode  # type: ignore[return-value]


# ---------------------------------------------------------------------------
# R1b — pure freshness / regen decision (no asyncio, no shared state)
# ---------------------------------------------------------------------------

def _should_regenerate(file_path: Path, file_action: "FileAction", no_cache: bool) -> bool:
    """Return True if the dynamic file needs to be (re)generated.

    True when the file is absent, ``no_cache`` is set, or the cached copy is stale.
    Callers must not call this for STATIC actions.
    """
    return (
        not file_path.is_file()
        or no_cache
        or not is_file_fresh(file_path, file_action.max_age_s)
    )


# ---------------------------------------------------------------------------
# R1a — pure validation / lookup helper (no asyncio, no shared state)
# ---------------------------------------------------------------------------

def _resolve_and_validate(filename: str, data_dir: Path) -> tuple["FileAction", Path]:
    """Validate *filename* and return ``(file_action, file_path)``.

    Raises ``HTTPNotFound`` for path-traversal attempts or unknown filenames.
    Does NOT check whether the file exists on disk.

    Checkpoint partial files (e.g. *.partial.json) are accepted when they
    correspond to a known dynamic FILE_ACTION_MAP entry. They are served as
    STATIC with max_age_s=0; a 404 is returned when the file is absent.
    """
    if not _safe_filename(filename):
        raise aiohttp.web.HTTPNotFound()
    file_action = get_file_action(filename)
    if file_action is None:
        if filename.lower() not in _CHECKPOINT_FILENAMES:
            raise aiohttp.web.HTTPNotFound(reason=f"Unknown filename: {filename}")
        file_action = _CHECKPOINT_FILE_ACTION
    return file_action, data_dir / filename


# ---------------------------------------------------------------------------
# R2a — long-cost (202 + polling) dispatch
# (touches _job_registry, _background_tasks, _job_runtime_registry)
# ---------------------------------------------------------------------------

async def _dispatch_long_cost(
    filename: str,
    action_args: list[str],
    data_dir: Path,
    file_action: "FileAction",
) -> aiohttp.web.Response:
    """Dispatch a long-cost or force_async action via 202 + polling.

    Deduplicates against an already-running job for the same filename.
    Spawns a background Task anchored in ``_background_tasks``.
    Returns a 202 Response immediately.
    Touches: ``_job_registry``, ``_background_tasks``,
    ``_job_runtime_registry``.
    """
    # Re-use an existing job for the same filename if already running.
    existing_job = next(
        (
            j for j in _job_registry.values()
            if j.filename == filename and j.status == JOB_STATUS_RUNNING
        ),
        None,
    )
    if existing_job is not None:
        job_id = existing_job.job_id
    else:
        job_id = str(uuid.uuid4())
        job = JobStatus(
            job_id=job_id,
            filename=filename,
            status=JOB_STATUS_RUNNING,
        )
        _job_registry[job_id] = job

        async def _run_job(
            jid: str = job_id,
            args: list[str] = action_args,
            ddir: Path = data_dir,
            tmo: float = file_action.action_cost_s * 1.5,
        ) -> None:
            try:
                # Acquire per-source lock so that only one long-cost subprocess
                # per source runs at a time.  The 202 was already returned to the
                # client; this serialization is transparent to the caller.
                source = args[0]
                async with _get_source_lock(source):
                    # Cancellation may happen while queued on the source lock.
                    j = _job_registry.get(jid)
                    if j is None:
                        return
                    if j.status == JOB_STATUS_CANCELLING:
                        j.status = JOB_STATUS_CANCELLED
                        if not j.detail:
                            j.detail = _JOB_CANCEL_GRACE_DETAIL
                        return

                    try:
                        exit_code = await run_td_cli(
                            args,
                            ddir,
                            timeout_s=tmo,
                            on_process_started=lambda process: _set_job_runtime_process(
                                jid, process
                            ),
                            on_process_ended=lambda: _set_job_runtime_process(jid, None),
                        )
                    except TypeError as exc:
                        # Backward-compatible fallback for tests/mocks that
                        # patch run_td_cli with the older signature.
                        if (
                            "on_process_started" not in str(exc)
                            and "on_process_ended" not in str(exc)
                        ):
                            raise
                        exit_code = await run_td_cli(args, ddir, timeout_s=tmo)
            except asyncio.CancelledError:
                j = _job_registry.get(jid)
                if j is not None and j.status == JOB_STATUS_CANCELLING:
                    j.status = JOB_STATUS_CANCELLED
                    if not j.detail:
                        j.detail = _JOB_CANCEL_GRACE_DETAIL
                raise

            j = _job_registry.get(jid)
            if j is None:
                return
            if j.status == JOB_STATUS_CANCELLING:
                j.status = JOB_STATUS_CANCELLED
                if not j.detail:
                    j.detail = _JOB_CANCEL_GRACE_DETAIL
                return
            if exit_code == 0:
                j.status = JOB_STATUS_DONE
            else:
                j.status = JOB_STATUS_ERROR
                j.detail = f"td_cli exit code {exit_code}"

        _t = asyncio.create_task(_run_job())
        _job_runtime_registry[job_id] = JobRuntime(
            job_id=job_id,
            filename=filename,
            source=action_args[0],
            task=_t,
        )
        _job_id_by_task[_t] = job_id
        _background_tasks.add(_t)
        _t.add_done_callback(_on_background_task_done)

    body = json.dumps(
        {"job_id": job_id, "status": JOB_STATUS_RUNNING, "filename": filename}
    )
    return aiohttp.web.Response(
        status=202,
        content_type="application/json",
        text=body,
        headers={"Location": f"/api/job/{job_id}"},
    )


# ---------------------------------------------------------------------------
# R2b — short-cost (synchronous) dispatch (touches _active_processes, _source_locks)
# ---------------------------------------------------------------------------

async def _dispatch_short_cost(
    filename: str,
    action_args: list[str],
    data_dir: Path,
    file_action: "FileAction",
    no_cache: bool,
) -> None:
    """Run a short-cost action synchronously, blocking until td_cli exits.

    Joins an in-flight task for the same filename when one exists.
    Acquires the per-source lock to prevent concurrent subprocess collisions.
    Raises ``HTTPBadGateway`` on subprocess failure.
    Touches: ``_active_processes``, ``_source_locks``.
    """
    file_path = data_dir / filename

    if filename in _active_processes:
        # Same file already in flight — join the existing task rather than
        # spawning a second subprocess.
        logging.info("Awaiting existing td_cli task for %s", filename)
        try:
            await _active_processes[filename]
        except Exception as exc:
            logging.warning("In-flight task for %s failed: %s", filename, exc)
            raise
        if not file_path.is_file():
            raise aiohttp.web.HTTPBadGateway(
                reason=f"td_cli failed for {filename}")
    else:
        # Different file but possibly same source — acquire the per-source lock
        # so that only one otbr-cli (or mdns, etc.) subprocess runs at a time.
        source = action_args[0]
        lock = _get_source_lock(source)
        async with lock:
            # Re-check freshness: another coroutine may have generated this
            # file while we waited for the source lock.
            if is_file_fresh(file_path, file_action.max_age_s) and not no_cache:
                pass  # fall through to serve the now-fresh file
            else:
                task: asyncio.Task[int] = asyncio.create_task(
                    run_td_cli(
                        action_args,
                        data_dir,
                        timeout_s=file_action.action_cost_s * 1.5,
                    )
                )
                _active_processes[filename] = task
                try:
                    exit_code = await task
                finally:
                    _active_processes.pop(filename, None)
                if exit_code != 0:
                    raise aiohttp.web.HTTPBadGateway(
                        reason=f"td_cli failed for {filename} (exit {exit_code})"
                    )


async def handle_data_api(request: aiohttp.web.Request) -> aiohttp.web.Response:
    """GET /api/data/{filename} — serve or regenerate a data file.

    Validation and lookup  → _resolve_and_validate
    Freshness decision     → _should_regenerate
    Long-cost dispatch     → _dispatch_long_cost  (202 + polling)
    Short-cost dispatch    → _dispatch_short_cost (synchronous)
    Response building      → _build_file_response
    """
    filename = request.match_info["filename"]
    data_dir: Path = request.app["td_data_dir"]
    cc = parse_request_cache_control(request.headers.get("Cache-Control"))
    no_cache = bool(cc.get("no-cache", False))

    file_action, file_path = _resolve_and_validate(filename, data_dir)

    logging.debug(">>>>>>>>>")
    logging.debug("Request for %s (no_cache=%s); file action: %s; file path: %s",
                  filename, no_cache, file_action, file_path)

    if file_action.action == "STATIC":
        if not file_path.is_file():
            raise aiohttp.web.HTTPNotFound(
                reason=f"Static file not found: {filename}")
    elif _should_regenerate(file_path, file_action, no_cache):
        action_args: list[str] = file_action.action  # type: ignore[assignment]
        if file_action.force_async or file_action.action_cost_s > _LONG_COST_THRESHOLD_S:
            return await _dispatch_long_cost(filename, action_args, data_dir, file_action)
        await _dispatch_short_cost(filename, action_args, data_dir, file_action, no_cache)

    logging.debug("Serving file %s for request (no_cache=%s)", file_path, no_cache)
    logging.debug("<<<<<<<<<")

    return _build_file_response(file_path, file_action, request)


# ---------------------------------------------------------------------------
# R1c — pure file-read / response builder (no asyncio, no shared state)
# ---------------------------------------------------------------------------

def _etag_matches(etag: str, header: str) -> bool:
    """Weak ETag comparison for If-None-Match (RFC 9110 §8.8.3).

    Returns True if *etag* (bare, unquoted strong ETag value) matches any
    token in the comma-separated *header* string using weak comparison:
    the ``W/`` prefix and surrounding quotes are stripped before comparing.
    A wildcard ``*`` always matches.
    """
    header = header.strip()
    if header == "*":
        return True
    for token in header.split(","):
        token = token.strip()
        if token.startswith("W/"):
            token = token[2:]
        if token.startswith('"') and token.endswith('"'):
            token = token[1:-1]
        if token == etag:
            return True
    return False


def _build_file_response(
    file_path: Path,
    file_action: "FileAction",
    request: aiohttp.web.Request | None = None,
) -> aiohttp.web.Response:
    """Read *file_path* from disk and return a Response with cache headers.

    Checks ``If-None-Match`` and ``If-Modified-Since`` request headers and
    returns ``304 Not Modified`` when the cached copy is still valid,
    avoiding retransmission of unchanged data files.
    Raises ``HTTPInternalServerError`` on OS failure.
    """
    try:
        st = file_path.stat()
    except OSError as exc:
        logging.error("Failed to stat %s: %s", file_path, exc)
        raise aiohttp.web.HTTPInternalServerError()

    file_mtime: float = st.st_mtime
    etag = f"{st.st_mtime_ns:x}-{st.st_size:x}"
    cache_headers = build_cache_response_headers(
        file_action.max_age_s, file_mtime)
    cache_headers["ETag"] = f'"{etag}"'

    # Conditional GET — If-None-Match takes precedence over If-Modified-Since
    # per RFC 9110 §13.1.2 and §13.1.3.
    if request is not None:
        ifnonematch = request.headers.get("If-None-Match")
        if ifnonematch is not None:
            if _etag_matches(etag, ifnonematch):
                return aiohttp.web.Response(status=304, headers=cache_headers)
        else:
            ifsince = request.headers.get("If-Modified-Since")
            if ifsince:
                try:
                    modsince_ts = email.utils.parsedate_to_datetime(
                        ifsince).timestamp()
                    if file_mtime <= modsince_ts:
                        return aiohttp.web.Response(status=304, headers=cache_headers)
                except Exception:
                    pass  # malformed header; fall through to serve the full response

    try:
        payload = file_path.read_bytes()
    except OSError as exc:
        logging.error("Failed to read %s: %s", file_path, exc)
        raise aiohttp.web.HTTPInternalServerError()

    suffix = file_path.suffix.lower()
    content_type = "application/json" if suffix == ".json" else "application/octet-stream"

    return aiohttp.web.Response(
        body=payload,
        content_type=content_type,
        headers=cache_headers,
    )


async def handle_job_api(request: aiohttp.web.Request) -> aiohttp.web.Response:
    """GET /api/job/{job_id} — poll the status of a long-running td_cli job."""
    job_id = request.match_info["job_id"]
    job = _job_registry.get(job_id)
    if job is None:
        raise aiohttp.web.HTTPNotFound(reason=f"Unknown job: {job_id}")

    body = _build_job_poll_body(job)
    if job.status in {JOB_STATUS_RUNNING, JOB_STATUS_CANCELLING}:
        data_dir = request.app.get("td_data_dir")
        if isinstance(data_dir, Path):
            body.update(_build_checkpoint_poll_metadata(job.filename, data_dir))

    return aiohttp.web.Response(
        content_type="application/json",
        text=json.dumps(body),
    )


async def handle_job_cancel_api(request: aiohttp.web.Request) -> aiohttp.web.Response:
    """DELETE /api/job/{job_id} — request cancellation of a long-running job."""
    job_id = request.match_info["job_id"]
    job = _job_registry.get(job_id)
    if job is None:
        raise aiohttp.web.HTTPNotFound(reason=f"Unknown job: {job_id}")

    if job.status == JOB_STATUS_CANCELLING:
        body = {
            "job_id": job_id,
            "status": JOB_STATUS_CANCELLING,
            "filename": job.filename,
            "detail": job.detail,
        }
        return aiohttp.web.Response(
            status=202,
            content_type="application/json",
            text=json.dumps(body),
        )

    if not _is_cancellable_job_status(job.status):
        body = {
            "job_id": job_id,
            "status": job.status,
            "filename": job.filename,
            "detail": job.detail,
            "error": "Job is not cancellable in its current state.",
        }
        logging.warning("Cancellation requested for non-cancellable job %s: %s",
                        job_id, body["error"])
        return aiohttp.web.Response(
            status=409,
            content_type="application/json",
            text=json.dumps(body),
        )

    job.status = JOB_STATUS_CANCELLING
    if not job.detail:
        job.detail = _JOB_CANCEL_GRACE_DETAIL

    runtime = _job_runtime_registry.get(job_id)
    if runtime is not None:
        process = runtime.process
        if process is not None and process.returncode is None and not runtime.task.done():
            # Cancel task; run_td_cli handles graceful terminate/kill cleanup.
            logging.info("Cancelling job %s: terminating subprocess", job_id)
            runtime.task.cancel()
        elif process is None and not runtime.task.done():
            # If still queued before subprocess start, cancel the task directly.
            logging.info("Cancelling job %s: task not started yet", job_id)
            runtime.task.cancel()

    body = {
        "job_id": job_id,
        "status": JOB_STATUS_CANCELLING,
        "filename": job.filename,
        "detail": job.detail,
    }
    return aiohttp.web.Response(
        status=202,
        content_type="application/json",
        text=json.dumps(body),
    )


async def handle_root(request: aiohttp.web.Request) -> aiohttp.web.Response:
    """Redirect / to /tdash.html."""
    raise aiohttp.web.HTTPFound("/tdash.html")


async def _set_static_cache_headers(
    request: aiohttp.web.Request,
    response: aiohttp.web.StreamResponse,
) -> None:
    """Add Cache-Control: no-cache to static asset responses.

    Skips /api/ routes (which set their own Cache-Control via
    build_cache_response_headers) and any response that already carries a
    Cache-Control header.  Because aiohttp's FileResponse always emits ETag
    and Last-Modified, no-cache causes browsers to revalidate with a
    conditional GET (If-None-Match / If-Modified-Since) and receive a 304
    when the file is unchanged — correct behaviour without wasted bandwidth.
    """
    if request.path.startswith("/api/"):
        return
    if "Cache-Control" not in response.headers:
        response.headers["Cache-Control"] = "no-cache"


# ---------------------------------------------------------------------------
# End 
# ---------------------------------------------------------------------------


def _non_negative_int(value: str) -> int:
    """argparse type: parse a non-negative integer."""
    try:
        parsed = int(value)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(
            f"invalid int value: {value!r}"
        ) from exc
    if parsed < 0:
        raise argparse.ArgumentTypeError(
            f"value must be >= 0, got {value!r}"
        )
    return parsed


def _resolve_file_cache_max_age(
    args: argparse.Namespace,
    parser: argparse.ArgumentParser,
) -> tuple[int, str]:
    """Resolve cache max-age using CLI > ENV > default precedence."""
    if args.file_cache_max_age is not None:
        return args.file_cache_max_age, "cli"

    env_raw = os.environ.get(TD_FILE_CACHE_MAX_AGE_ENV_NAME)
    if env_raw is not None:
        try:
            parsed = int(env_raw)
        except ValueError:
            parser.error(
                f"Invalid {TD_FILE_CACHE_MAX_AGE_ENV_NAME} value: {env_raw!r}; "
                "expected a non-negative integer."
            )
        if parsed < 0:
            parser.error(
                f"Invalid {TD_FILE_CACHE_MAX_AGE_ENV_NAME} value: {env_raw!r}; "
                "expected a non-negative integer."
            )
        return parsed, "env"

    return TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, "default"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Start the Thread Network Topology Dashboard web server.",
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true",
        help="No-op: INFO logging is the default. Only --debug changes behaviour."
    )
    parser.add_argument(
        "--debug", "-d", action="store_true", help="Enable debug logging"
    )
    parser.add_argument(
        "--host",
        default=os.environ.get("HOST", TD_WEB_HOST_ADDR),
        help=f"Host/address to bind to (default: '{TD_WEB_HOST_ADDR}', env: HOST)",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=int(os.environ.get("PORT", TD_WEB_HOST_PORT)),
        help=f"Port to listen on (default: {TD_WEB_HOST_PORT}, env: PORT)",
    )
    parser.add_argument(
        "--file-cache-max-age",
        type=_non_negative_int,
        default=None,
        metavar="SECONDS",
        help=(
            f"Default max-age in seconds for data files "
            f"(CLI > {TD_FILE_CACHE_MAX_AGE_ENV_NAME} > "
            f"{TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT})"
        ),
    )
    parser.add_argument("--datadir", default=None, help=TD_DATA_DIR_ARG_HELP)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    logging.basicConfig(
        level=logging.INFO, format="[%(asctime)s] %(levelname)s: %(message)s"
    )

    parser = build_parser()
    args = parser.parse_args(argv)
    cache_max_age_s, cache_max_age_source = _resolve_file_cache_max_age(args, parser)
    _set_default_file_cache_max_age(cache_max_age_s)

    # Apply verbosity / debug flags
    if args.debug:
        logging.getLogger().setLevel(logging.DEBUG)
    elif args.verbose:
        logging.getLogger().setLevel(logging.INFO)

    static_root = Path(__file__).resolve().parent
    td_data_dir_resolution = resolve_data_dir_with_source(
        data_dir=args.datadir)
    td_data_dir = td_data_dir_resolution.path

    logging.info(format_data_dir_log_message(td_data_dir_resolution))
    logging.info(
        "Data file cache max-age default: %s s (source: %s)",
        cache_max_age_s,
        cache_max_age_source,
    )

    app = aiohttp.web.Application()
    app["td_data_dir"] = td_data_dir

    async def _start_cleanup(app: aiohttp.web.Application) -> None:
        app["_cleanup_task"] = asyncio.create_task(
            _cleanup_job_registry_loop())

    async def _on_shutdown(app: aiohttp.web.Application) -> None:
        # Cancel the periodic cleanup task.
        cleanup_task: asyncio.Task | None = app.get("_cleanup_task")
        if cleanup_task is not None:
            cleanup_task.cancel()

        # Cancel short-cost synchronous tasks tracked by filename.
        short_tasks = list(_active_processes.values())
        for t in short_tasks:
            t.cancel()

        # Cancel all in-flight background job tasks and wait for them to finish.
        tasks = list(_background_tasks)
        for t in tasks:
            t.cancel()

        wait_tasks = short_tasks + tasks
        if wait_tasks:
            await asyncio.gather(*wait_tasks, return_exceptions=True)

        _active_processes.clear()
        _job_runtime_registry.clear()
        _job_id_by_task.clear()

    app.on_startup.append(_start_cleanup)
    app.on_shutdown.append(_on_shutdown)
    app.on_response_prepare.append(_set_static_cache_headers)

    # Configure CORS before registering routes so OPTIONS preflights are handled
    # automatically for all API endpoints.  Static assets and the root redirect
    # are not CORS-wrapped (same-origin by design).
    cors = aiohttp_cors.setup(
        app,
        defaults={
            "*": aiohttp_cors.ResourceOptions(
                allow_credentials=False,
                expose_headers="*",
                allow_headers="*",
            )
        },
    )

    # Specific routes are registered before the static catch-all.
    app.router.add_get("/", handle_root)
    cors.add(app.router.add_get("/api/data/{filename}", handle_data_api))
    cors.add(app.router.add_get("/api/job/{job_id}", handle_job_api))
    cors.add(app.router.add_delete("/api/job/{job_id}", handle_job_cancel_api))
    # Serve all static assets (HTML, JS, CSS, …) from the src/ directory.
    app.router.add_static(
        "/", static_root, show_index=False, follow_symlinks=False)

    logging.info("Starting tdash webserver dashboard (aiohttp)...")
    logging.info(
        "Serving at http://%s:%s (/ redirects to /tdash.html)",
        args.host or "localhost",
        args.port,
    )
    logging.info("Static files root: %s", static_root)
    logging.info("Data root: %s", td_data_dir)

    aiohttp.web.run_app(
        app,
        host=args.host if args.host else None,
        port=args.port,
        access_log=logging.getLogger("aiohttp.access"),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
