import asyncio
import dataclasses
import email.utils
import json
import mimetypes
import os
import argparse
import logging
import sys
import time
import uuid
from pathlib import Path
from typing import Sequence

import aiohttp.web
import aiohttp_cors

from util_data import (
    format_data_dir_log_message,
    resolve_data_dir_with_source,
)
from td_const import TD_DATA_DIR_ARG_HELP

TD_WEB_HOST_ADDR = ""
TD_WEB_HOST_PORT = 9165

# Default max-age for data files in seconds; can be overridden per-file in FILE_ACTION_MAP.
TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT = 86400  # 1 day in seconds

# ---------------------------------------------------------------------------
# Mapping table and cache helpers
# ---------------------------------------------------------------------------


@dataclasses.dataclass
class FileAction:
    """Describes how to obtain (or verify) a data file and its cache policy."""

    max_age_s: int
    # "STATIC" means the file is managed externally; never regenerated by the server.
    # A list of strings is passed as CLI arguments to td_cli.py.
    action: "str | list[str]"
    action_cost_s: int
    # When True the action is always dispatched via 202 + polling regardless of
    # action_cost_s.  Use this for any action whose worst-case duration exceeds
    # the browser-safe synchronous limit (~30 s) but is under _LONG_COST_THRESHOLD_S.
    force_async: bool = False


FILE_ACTION_MAP: dict[str, FileAction] = {
    # System
    # Externally managed; never regenerated by the server.
    "td-static-extaddr-device-label.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action="STATIC", action_cost_s=1
    ),

    # mdns
    # Fetches mDNS using zeroconf. Browse window is ~5–10 min per service type.
    "td-mdns-scopes-thread.json": FileAction(
        # ~10 min browse
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action=["mdns", "thread"], action_cost_s=600
    ),
    "td-mdns-scopes-br.json": FileAction(
        # ~6 min browse
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action=["mdns", "br"], action_cost_s=360
    ),
    "td-mdns-scopes-hap.json": FileAction(
        # ~6 min browse
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action=["mdns", "hap"], action_cost_s=360
    ),
    "td-mdns-scopes-matter.json": FileAction(
        # ~10 min browse
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action=["mdns", "matter"], action_cost_s=600
    ),

    # otbr-cli
    # Single ot-ctl commands — near-instant.
    "td-otbr-cli-thread-network-info.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action=["otbr-cli", "thread-network-info"], action_cost_s=1
    ),
    "td-otbr-cli-router-table.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action=["otbr-cli", "router-table"], action_cost_s=1
    ),
    # meshdiag topology — single command, a few seconds.
    "td-otbr-cli-meshdiag-topology.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action=["otbr-cli", "meshdiag", "topology"], action_cost_s=5
    ),
    # Per-router meshdiag commands — ~1–2 s each router; 90 s for ~50-router network.
    # force_async=True: 90 s exceeds the browser-safe synchronous limit (~30 s).
    "td-otbr-cli-meshdiag-router-childip6.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT,
        action=["otbr-cli", "meshdiag", "childip6"],
        action_cost_s=90,
        force_async=True,
    ),
    "td-otbr-cli-meshdiag-router-childtables.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT,
        action=["otbr-cli", "meshdiag", "childtable"],
        action_cost_s=90,  # ~1–2 s per router
        force_async=True,
    ),
    "td-otbr-cli-meshdiag-router-neighbortables.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT,
        action=["otbr-cli", "meshdiag", "routerneighbortable"],
        action_cost_s=90,  # ~1–2 s per router
        force_async=True,
    ),
    # networkdiag — TLV request per router with retries; up to ~8 min on large networks.
    "td-otbr-cli-networkdiag-topology-poll.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT,
        action=["otbr-cli", "networkdiag", "topology-poll"],
        action_cost_s=480,  # ~8 min for ~60 routers with timeout retries
    ),
    # networkdiag topology-multicast-network — TLV request per router with retries; up to ~16 seconds on large networks.
    "td-otbr-cli-networkdiag-topology-multicast-network.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT,
        action=["otbr-cli", "networkdiag", "topology-multicast-network"],
        action_cost_s=16,  # ~11 seconds with timeout retries
    ),
    # networkdiag topology-multicast-neighbors — TLV request per router with retries; up to ~16 seconds on large networks.
    "td-otbr-cli-networkdiag-topology-multicast-neighbors.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT,
        action=["otbr-cli", "networkdiag", "topology-multicast-neighbors"],
        action_cost_s=16,  # ~11 seconds with timeout retries
    ),

    # otbr-restapi
    # REST API downloads — single HTTP call, near-instant.
    "td-otbr-restapi-dataset-active.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action=["otbr-restapi", "download"], action_cost_s=1
    ),
    "td-otbr-restapi-devices.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action=["otbr-restapi", "download"], action_cost_s=1
    ),
    "td-otbr-restapi-diagnostics.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action=["otbr-restapi", "download"], action_cost_s=1
    ),
    "td-otbr-restapi-devices-list.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action=["otbr-restapi", "devices", "list"], action_cost_s=1
    ),
    "td-otbr-restapi-devices-fetch.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action=["otbr-restapi", "devices", "fetch"], action_cost_s=180
    ),    
    "td-otbr-restapi-diagnostics-list.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action=["otbr-restapi", "diagnostics", "list"], action_cost_s=1
    ),
    "td-otbr-restapi-actions-list.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action=["otbr-restapi", "actions", "list"], action_cost_s=1
    ),
    "td-otbr-restapi-mesh-diagnostics-fetch-all.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action=["otbr-restapi", "mesh-diagnostics", "fetch-all"], action_cost_s=480
    ),
    "td-otbr-restapi-diagnostics-fetch-all.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action=["otbr-restapi", "diagnostics", "fetch-all"], action_cost_s=480
    ),

    # Eve topology exports — externally managed static files.
    "Eve Thread Network Layout.evethreadlayout": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action="STATIC", action_cost_s=1
    ),
    "td-eve-topology.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action="STATIC", action_cost_s=1
    ),

    # Pre-merged output — produced by dataset_merge; treated as static here.
    "td-merged-topology-all.json": FileAction(
        max_age_s=TD_DATA_FILE_CACHE_MAX_AGE_DEFAULT, action="STATIC", action_cost_s=1
    ),
}


# Normalised lowercase lookup table built once at import time so that
# get_file_action() is O(1) instead of O(n) for every request.
_FILE_ACTION_MAP_LOWER: dict[str, FileAction] = {
    k.lower(): v for k, v in FILE_ACTION_MAP.items()
}


def get_file_action(filename: str) -> FileAction | None:
    """Case-insensitive O(1) lookup in FILE_ACTION_MAP.

    Returns the matching FileAction, or None if the filename is unknown.
    """
    return _FILE_ACTION_MAP_LOWER.get(filename.lower())


def is_file_fresh(file_path: Path, max_age_s: int) -> bool:
    """Return True if *file_path* exists and its mtime is within *max_age_s* seconds."""
    try:
        mtime = file_path.stat().st_mtime
    except FileNotFoundError:
        return False
    return (time.time() - mtime) < max_age_s


def parse_request_cache_control(header_value: str | None) -> dict:
    """Parse a Cache-Control request header string into a dict.

    Examples::

        parse_request_cache_control("no-cache")
        # -> {"no-cache": True}

        parse_request_cache_control("max-age=600, no-store")
        # -> {"max-age": 600, "no-store": True}

        parse_request_cache_control(None)
        # -> {}
    """
    if not header_value:
        return {}
    result: dict = {}
    for directive in header_value.split(","):
        directive = directive.strip()
        if "=" in directive:
            name, _, value = directive.partition("=")
            name = name.strip().lower()
            value = value.strip()
            try:
                result[name] = int(value)
            except ValueError:
                result[name] = value
        else:
            result[directive.lower()] = True
    return result


def build_cache_response_headers(max_age_s: int, file_mtime: float) -> dict[str, str]:
    """Return HTTP response headers for cache control.

    Returns a dict with ``Cache-Control`` and ``Last-Modified`` headers.
    ``Last-Modified`` reflects the file's actual modification time so that
    conditional GET (``If-Modified-Since``) works correctly.
    """
    last_modified = email.utils.formatdate(file_mtime, usegmt=True)
    return {
        "Cache-Control": f"max-age={max_age_s}",
        "Last-Modified": last_modified,
    }


# ---------------------------------------------------------------------------
# End
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# aiohttp async server
# ---------------------------------------------------------------------------

# Ensure .mjs and other types are served with the right Content-Type on
# minimal container images where the OS mime database may be absent.
mimetypes.add_type("application/javascript", ".js")
mimetypes.add_type("application/javascript", ".mjs")
mimetypes.add_type("application/json", ".json")
mimetypes.add_type("text/css", ".css")
mimetypes.add_type("text/html", ".html")

# Keyed by *filename*; value is the asyncio.Task running run_td_cli for that file.
# Serves two purposes for the short-cost synchronous path:
#   1. Deduplication key — detect whether this exact file is already being generated.
#   2. Awaitable handle — late-arriving requests for the same file can join (await)
#      the in-flight task instead of spawning a second subprocess.
# Note: source-level serialization (preventing two different files of the same source
# from running concurrently) is handled separately via _source_locks / _get_source_lock.
_active_processes: dict[str, "asyncio.Task[int]"] = {}

# Keyed by source name (action[0], e.g. "otbr-cli", "mdns", "otbr-restapi").
# Each lock serializes all td_cli subprocesses for that source so that only one
# runs at a time, preventing hardware/socket conflicts in the underlying CLI layer.
# In a long-lived server with many unique source keys this dict could grow
# unbounded. If that becomes a concern, add periodic cleanup (e.g. evict locks
# that are not locked and have not been used recently).
_source_locks: dict[str, asyncio.Lock] = {}


def _get_source_lock(source: str) -> asyncio.Lock:
    """Return the asyncio.Lock for *source*, creating it lazily if absent."""
    if source not in _source_locks:
        _source_locks[source] = asyncio.Lock()
    return _source_locks[source]


# async job tracking
_LONG_COST_THRESHOLD_S = 300  # actions with cost > this get 202 + polling


@dataclasses.dataclass
class JobStatus:
    job_id: str
    filename: str
    status: str  # "running" | "done" | "error"
    detail: str = ""
    created_at: float = dataclasses.field(default_factory=time.time)


# Registry of in-flight and recently-completed jobs.
_job_registry: dict[str, JobStatus] = {}

# Anchor set that keeps references to fire-and-forget background Tasks so the
# garbage collector cannot collect them before they complete (CPython allows GC
# of Task objects that have no other referents).
_background_tasks: set["asyncio.Task[None]"] = set()

# Cleanup schedule for the job registry.
_JOB_TTL_S = 900       # evict completed/errored jobs after 15 minutes
_CLEANUP_INTERVAL_S = 60  # run eviction sweep every 60 seconds


def _on_background_task_done(task: "asyncio.Task[None]") -> None:
    """Done-callback: discard the task from the anchor set and log any exception."""
    _background_tasks.discard(task)
    if not task.cancelled():
        exc = task.exception()
        if exc is not None:
            logging.error(
                "Background job task raised an unhandled exception: %s",
                exc,
                exc_info=exc,
            )


async def _cleanup_job_registry_loop() -> None:
    """Periodically evict completed/errored jobs older than _JOB_TTL_S."""
    while True:
        await asyncio.sleep(_CLEANUP_INTERVAL_S)
        now = time.time()
        expired = [
            jid
            for jid, j in list(_job_registry.items())
            if j.status != "running" and (now - j.created_at) > _JOB_TTL_S
        ]
        for jid in expired:
            _job_registry.pop(jid, None)
        if expired:
            logging.debug(
                "Evicted %d expired job(s) from registry", len(expired))


def _safe_filename(filename: str) -> bool:
    """Return True if *filename* contains no path-traversal characters."""
    return (
        bool(filename)
        and "/" not in filename
        and "\\" not in filename
        and ".." not in filename
        and "\x00" not in filename
    )


async def run_td_cli(
    action_args: list[str],
    data_dir: Path,
    *,
    timeout_s: float | None = None,
) -> int:
    """Invoke td_cli.py as a subprocess and return its exit code.

    *timeout_s* is the hard wall-clock deadline for the subprocess.  When the
    deadline expires the process is killed and ``asyncio.TimeoutError`` is
    re-raised to the caller.  Pass ``None`` (the default) to disable the
    timeout.
    """
    td_cli_path = Path(__file__).parent / "td_cli.py"
    logging.debug("Spawning subprocess: %s %s %s", 
                  sys.executable,
                  td_cli_path, 
                  " ".join(action_args))
    process = await asyncio.create_subprocess_exec(
        sys.executable,
        str(td_cli_path),
        "--datadir", str(data_dir),  # must precede action_args so td_cli.py's
        *action_args,                # top-level parser captures it before subcommand delegation
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    _t0 = time.monotonic()
    try:
        if timeout_s is not None:
            stdout, stderr = await asyncio.wait_for(
                process.communicate(), timeout=timeout_s
            )
        else:
            stdout, stderr = await process.communicate()
    except asyncio.TimeoutError:
        logging.warning(
            "Subprocess timed out after %.1f s (args: %s); killing process",
            timeout_s,
            sys.executable,
            td_cli_path,
            " ".join(action_args),
            )
        process.kill()
        # reap the child to avoid zombie
        await process.communicate()  
        raise
    finally:
        logging.debug(
            "Subprocess elapsed %.3f s  %s %s %s",
            time.monotonic() - _t0,
            sys.executable,
            td_cli_path,
            " ".join(action_args)
        )
    if stdout:
        logging.info("td_cli stdout: %s", stdout.decode(errors="replace"))
    if stderr:
        logging.warning("td_cli stderr: %s", stderr.decode(errors="replace"))
    return process.returncode  # type: ignore[return-value]


# ---------------------------------------------------------------------------
# R1b — pure freshness / regen decision (no asyncio, no shared state)
# ---------------------------------------------------------------------------

def _should_regenerate(file_path: Path, file_action: "FileAction", no_cache: bool) -> bool:
    """Return True if the dynamic file needs to be (re)generated.

    True when the file is absent, ``no_cache`` is set, or the cached copy is stale.
    Callers must not call this for STATIC actions.
    """
    return (
        not file_path.is_file()
        or no_cache
        or not is_file_fresh(file_path, file_action.max_age_s)
    )


# ---------------------------------------------------------------------------
# R1a — pure validation / lookup helper (no asyncio, no shared state)
# ---------------------------------------------------------------------------

def _resolve_and_validate(filename: str, data_dir: Path) -> tuple["FileAction", Path]:
    """Validate *filename* and return ``(file_action, file_path)``.

    Raises ``HTTPNotFound`` for path-traversal attempts or unknown filenames.
    Does NOT check whether the file exists on disk.
    """
    if not _safe_filename(filename):
        raise aiohttp.web.HTTPNotFound()
    file_action = get_file_action(filename)
    if file_action is None:
        raise aiohttp.web.HTTPNotFound(reason=f"Unknown filename: {filename}")
    return file_action, data_dir / filename


# ---------------------------------------------------------------------------
# R2a — long-cost (202 + polling) dispatch (touches _job_registry, _background_tasks)
# ---------------------------------------------------------------------------

async def _dispatch_long_cost(
    filename: str,
    action_args: list[str],
    data_dir: Path,
    file_action: "FileAction",
) -> aiohttp.web.Response:
    """Dispatch a long-cost or force_async action via 202 + polling.

    Deduplicates against an already-running job for the same filename.
    Spawns a background Task anchored in ``_background_tasks``.
    Returns a 202 Response immediately.
    Touches: ``_job_registry``, ``_background_tasks``.
    """
    # Re-use an existing job for the same filename if already running.
    existing_job = next(
        (
            j for j in _job_registry.values()
            if j.filename == filename and j.status == "running"
        ),
        None,
    )
    if existing_job is not None:
        job_id = existing_job.job_id
    else:
        job_id = str(uuid.uuid4())
        job = JobStatus(job_id=job_id, filename=filename, status="running")
        _job_registry[job_id] = job

        async def _run_job(
            jid: str = job_id,
            args: list[str] = action_args,
            ddir: Path = data_dir,
            tmo: float = file_action.action_cost_s * 1.5,
        ) -> None:
            # Acquire per-source lock so that only one long-cost subprocess
            # per source runs at a time.  The 202 was already returned to the
            # client; this serialization is transparent to the caller.
            source = args[0]
            async with _get_source_lock(source):
                exit_code = await run_td_cli(args, ddir, timeout_s=tmo)
            j = _job_registry.get(jid)
            if j is None:
                return
            if exit_code == 0:
                j.status = "done"
            else:
                j.status = "error"
                j.detail = f"td_cli exit code {exit_code}"

        _t = asyncio.create_task(_run_job())
        _background_tasks.add(_t)
        _t.add_done_callback(_on_background_task_done)

    body = json.dumps(
        {"job_id": job_id, "status": "running", "filename": filename}
    )
    return aiohttp.web.Response(
        status=202,
        content_type="application/json",
        text=body,
        headers={"Location": f"/api/job/{job_id}"},
    )


# ---------------------------------------------------------------------------
# R2b — short-cost (synchronous) dispatch (touches _active_processes, _source_locks)
# ---------------------------------------------------------------------------

async def _dispatch_short_cost(
    filename: str,
    action_args: list[str],
    data_dir: Path,
    file_action: "FileAction",
    no_cache: bool,
) -> None:
    """Run a short-cost action synchronously, blocking until td_cli exits.

    Joins an in-flight task for the same filename when one exists.
    Acquires the per-source lock to prevent concurrent subprocess collisions.
    Raises ``HTTPBadGateway`` on subprocess failure.
    Touches: ``_active_processes``, ``_source_locks``.
    """
    file_path = data_dir / filename

    if filename in _active_processes:
        # Same file already in flight — join the existing task rather than
        # spawning a second subprocess.
        logging.info("Awaiting existing td_cli task for %s", filename)
        try:
            await _active_processes[filename]
        except Exception as exc:
            logging.warning("In-flight task for %s failed: %s", filename, exc)
            raise
        if not file_path.is_file():
            raise aiohttp.web.HTTPBadGateway(
                reason=f"td_cli failed for {filename}")
    else:
        # Different file but possibly same source — acquire the per-source lock
        # so that only one otbr-cli (or mdns, etc.) subprocess runs at a time.
        source = action_args[0]
        lock = _get_source_lock(source)
        async with lock:
            # Re-check freshness: another coroutine may have generated this
            # file while we waited for the source lock.
            if is_file_fresh(file_path, file_action.max_age_s) and not no_cache:
                pass  # fall through to serve the now-fresh file
            else:
                task: asyncio.Task[int] = asyncio.create_task(
                    run_td_cli(
                        action_args,
                        data_dir,
                        timeout_s=file_action.action_cost_s * 1.5,
                    )
                )
                _active_processes[filename] = task
                try:
                    exit_code = await task
                finally:
                    _active_processes.pop(filename, None)
                if exit_code != 0:
                    raise aiohttp.web.HTTPBadGateway(
                        reason=f"td_cli failed for {filename} (exit {exit_code})"
                    )


async def handle_data_api(request: aiohttp.web.Request) -> aiohttp.web.Response:
    """GET /api/data/{filename} — serve or regenerate a data file.

    Validation and lookup  → _resolve_and_validate
    Freshness decision     → _should_regenerate
    Long-cost dispatch     → _dispatch_long_cost  (202 + polling)
    Short-cost dispatch    → _dispatch_short_cost (synchronous)
    Response building      → _build_file_response
    """
    filename = request.match_info["filename"]
    data_dir: Path = request.app["td_data_dir"]
    cc = parse_request_cache_control(request.headers.get("Cache-Control"))
    no_cache = bool(cc.get("no-cache", False))

    file_action, file_path = _resolve_and_validate(filename, data_dir)

    logging.debug(">>>>>>>>>")
    logging.debug("Request for %s (no_cache=%s); file action: %s; file path: %s",
                  filename, no_cache, file_action, file_path)

    if file_action.action == "STATIC":
        if not file_path.is_file():
            raise aiohttp.web.HTTPNotFound(
                reason=f"Static file not found: {filename}")
    elif _should_regenerate(file_path, file_action, no_cache):
        action_args: list[str] = file_action.action  # type: ignore[assignment]
        if file_action.force_async or file_action.action_cost_s > _LONG_COST_THRESHOLD_S:
            return await _dispatch_long_cost(filename, action_args, data_dir, file_action)
        await _dispatch_short_cost(filename, action_args, data_dir, file_action, no_cache)

    logging.debug("Serving file %s for request (no_cache=%s)", file_path, no_cache)
    logging.debug("<<<<<<<<<")

    return _build_file_response(file_path, file_action, request)


# ---------------------------------------------------------------------------
# R1c — pure file-read / response builder (no asyncio, no shared state)
# ---------------------------------------------------------------------------

def _etag_matches(etag: str, header: str) -> bool:
    """Weak ETag comparison for If-None-Match (RFC 9110 §8.8.3).

    Returns True if *etag* (bare, unquoted strong ETag value) matches any
    token in the comma-separated *header* string using weak comparison:
    the ``W/`` prefix and surrounding quotes are stripped before comparing.
    A wildcard ``*`` always matches.
    """
    header = header.strip()
    if header == "*":
        return True
    for token in header.split(","):
        token = token.strip()
        if token.startswith("W/"):
            token = token[2:]
        if token.startswith('"') and token.endswith('"'):
            token = token[1:-1]
        if token == etag:
            return True
    return False


def _build_file_response(
    file_path: Path,
    file_action: "FileAction",
    request: aiohttp.web.Request | None = None,
) -> aiohttp.web.Response:
    """Read *file_path* from disk and return a Response with cache headers.

    Checks ``If-None-Match`` and ``If-Modified-Since`` request headers and
    returns ``304 Not Modified`` when the cached copy is still valid,
    avoiding retransmission of unchanged data files.
    Raises ``HTTPInternalServerError`` on OS failure.
    """
    try:
        st = file_path.stat()
    except OSError as exc:
        logging.error("Failed to stat %s: %s", file_path, exc)
        raise aiohttp.web.HTTPInternalServerError()

    file_mtime: float = st.st_mtime
    etag = f"{st.st_mtime_ns:x}-{st.st_size:x}"
    cache_headers = build_cache_response_headers(
        file_action.max_age_s, file_mtime)
    cache_headers["ETag"] = f'"{etag}"'

    # Conditional GET — If-None-Match takes precedence over If-Modified-Since
    # per RFC 9110 §13.1.2 and §13.1.3.
    if request is not None:
        ifnonematch = request.headers.get("If-None-Match")
        if ifnonematch is not None:
            if _etag_matches(etag, ifnonematch):
                return aiohttp.web.Response(status=304, headers=cache_headers)
        else:
            ifsince = request.headers.get("If-Modified-Since")
            if ifsince:
                try:
                    modsince_ts = email.utils.parsedate_to_datetime(
                        ifsince).timestamp()
                    if file_mtime <= modsince_ts:
                        return aiohttp.web.Response(status=304, headers=cache_headers)
                except Exception:
                    pass  # malformed header; fall through to serve the full response

    try:
        payload = file_path.read_bytes()
    except OSError as exc:
        logging.error("Failed to read %s: %s", file_path, exc)
        raise aiohttp.web.HTTPInternalServerError()

    suffix = file_path.suffix.lower()
    content_type = "application/json" if suffix == ".json" else "application/octet-stream"

    return aiohttp.web.Response(
        body=payload,
        content_type=content_type,
        headers=cache_headers,
    )


async def handle_job_api(request: aiohttp.web.Request) -> aiohttp.web.Response:
    """GET /api/job/{job_id} — poll the status of a long-running td_cli job."""
    job_id = request.match_info["job_id"]
    job = _job_registry.get(job_id)
    if job is None:
        raise aiohttp.web.HTTPNotFound(reason=f"Unknown job: {job_id}")

    if job.status == "running":
        body = {"status": "running"}
    elif job.status == "done":
        body = {"status": "done", "filename": job.filename}
    else:
        body = {"status": "error", "detail": job.detail}

    return aiohttp.web.Response(
        content_type="application/json",
        text=json.dumps(body),
    )


async def handle_root(request: aiohttp.web.Request) -> aiohttp.web.Response:
    """Redirect / to /tdash.html."""
    raise aiohttp.web.HTTPFound("/tdash.html")


async def _set_static_cache_headers(
    request: aiohttp.web.Request,
    response: aiohttp.web.StreamResponse,
) -> None:
    """Add Cache-Control: no-cache to static asset responses.

    Skips /api/ routes (which set their own Cache-Control via
    build_cache_response_headers) and any response that already carries a
    Cache-Control header.  Because aiohttp's FileResponse always emits ETag
    and Last-Modified, no-cache causes browsers to revalidate with a
    conditional GET (If-None-Match / If-Modified-Since) and receive a 304
    when the file is unchanged — correct behaviour without wasted bandwidth.
    """
    if request.path.startswith("/api/"):
        return
    if "Cache-Control" not in response.headers:
        response.headers["Cache-Control"] = "no-cache"


# ---------------------------------------------------------------------------
# End 
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Start the Thread Network Topology Dashboard web server.",
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true",
        help="No-op: INFO logging is the default. Only --debug changes behaviour."
    )
    parser.add_argument(
        "--debug", "-d", action="store_true", help="Enable debug logging"
    )
    parser.add_argument(
        "--host",
        default=os.environ.get("HOST", TD_WEB_HOST_ADDR),
        help=f"Host/address to bind to (default: '{TD_WEB_HOST_ADDR}', env: HOST)",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=int(os.environ.get("PORT", TD_WEB_HOST_PORT)),
        help=f"Port to listen on (default: {TD_WEB_HOST_PORT}, env: PORT)",
    )
    parser.add_argument("--datadir", default=None, help=TD_DATA_DIR_ARG_HELP)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    logging.basicConfig(
        level=logging.INFO, format="[%(asctime)s] %(levelname)s: %(message)s"
    )

    parser = build_parser()
    args = parser.parse_args(argv)

    # Apply verbosity / debug flags
    if args.debug:
        logging.getLogger().setLevel(logging.DEBUG)
    elif args.verbose:
        logging.getLogger().setLevel(logging.INFO)

    static_root = Path(__file__).resolve().parent
    td_data_dir_resolution = resolve_data_dir_with_source(
        data_dir=args.datadir)
    td_data_dir = td_data_dir_resolution.path

    logging.info(format_data_dir_log_message(td_data_dir_resolution))

    app = aiohttp.web.Application()
    app["td_data_dir"] = td_data_dir

    async def _start_cleanup(app: aiohttp.web.Application) -> None:
        app["_cleanup_task"] = asyncio.create_task(
            _cleanup_job_registry_loop())

    async def _on_shutdown(app: aiohttp.web.Application) -> None:
        # Cancel the periodic cleanup task.
        cleanup_task: asyncio.Task | None = app.get("_cleanup_task")
        if cleanup_task is not None:
            cleanup_task.cancel()
        # Cancel all in-flight background job tasks and wait for them to finish.
        tasks = list(_background_tasks)
        for t in tasks:
            t.cancel()
        if tasks:
            await asyncio.gather(*tasks, return_exceptions=True)

    app.on_startup.append(_start_cleanup)
    app.on_shutdown.append(_on_shutdown)
    app.on_response_prepare.append(_set_static_cache_headers)

    # Configure CORS before registering routes so OPTIONS preflights are handled
    # automatically for all API endpoints.  Static assets and the root redirect
    # are not CORS-wrapped (same-origin by design).
    cors = aiohttp_cors.setup(
        app,
        defaults={
            "*": aiohttp_cors.ResourceOptions(
                allow_credentials=False,
                expose_headers="*",
                allow_headers="*",
            )
        },
    )

    # Specific routes are registered before the static catch-all.
    app.router.add_get("/", handle_root)
    cors.add(app.router.add_get("/api/data/{filename}", handle_data_api))
    cors.add(app.router.add_get("/api/job/{job_id}", handle_job_api))
    # Serve all static assets (HTML, JS, CSS, …) from the src/ directory.
    app.router.add_static(
        "/", static_root, show_index=False, follow_symlinks=False)

    logging.info("Starting tdash webserver dashboard (aiohttp)...")
    logging.info(
        "Serving at http://%s:%s (/ redirects to /tdash.html)",
        args.host or "localhost",
        args.port,
    )
    logging.info("Static files root: %s", static_root)
    logging.info("Data root: %s", td_data_dir)

    aiohttp.web.run_app(
        app,
        host=args.host if args.host else None,
        port=args.port,
        access_log=logging.getLogger("aiohttp.access"),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
