import asyncio
import dataclasses
import email.utils
import json
import mimetypes
import os
import argparse
import logging
import sys
import time
import uuid
from pathlib import Path
from typing import Sequence

import aiohttp.web

from util_data import (
    format_data_dir_log_message,
    resolve_data_dir_with_source,
)
from const import TD_DATA_DIR_ARG_HELP

TD_WEB_HOST_ADDR = ""
TD_WEB_HOST_PORT = 8087


# ---------------------------------------------------------------------------
# Phase 1 — Mapping table and cache helpers
# ---------------------------------------------------------------------------

@dataclasses.dataclass
class FileAction:
    """Describes how to obtain (or verify) a data file and its cache policy."""

    max_age_s: int
    # "STATIC" means the file is managed externally; never regenerated by the server.
    # A list of strings is passed as CLI arguments to td_cli.py.
    action: "str | list[str]"
    action_cost_s: int


FILE_ACTION_MAP: dict[str, FileAction] = {
    # Externally managed; never regenerated by the server.
    "td-static-extaddr-device-label.json": FileAction(
        max_age_s=3600, action="STATIC", action_cost_s=1
    ),
    # mDNS scans — zeroconf browse window is ~5–10 min per service type.
    "td-mdns-scopes-thread.json": FileAction(
        # ~10 min browse
        max_age_s=3600, action=["mdns", "thread"], action_cost_s=600
    ),
    "td-mdns-scopes-br.json": FileAction(
        # ~6 min browse
        max_age_s=3600, action=["mdns", "br"], action_cost_s=360
    ),
    "td-mdns-scopes-hap.json": FileAction(
        # ~6 min browse
        max_age_s=3600, action=["mdns", "hap"], action_cost_s=360
    ),
    "td-mdns-scopes-matter.json": FileAction(
        # ~10 min browse
        max_age_s=3600, action=["mdns", "matter"], action_cost_s=600
    ),
    # Single ot-ctl commands — near-instant.
    "td-otbr-cli-network-dataset-info.json": FileAction(
        max_age_s=3600, action=["otbr-cli", "network-dataset-info"], action_cost_s=1
    ),
    "td-otbr-cli-router-table.json": FileAction(
        max_age_s=3600, action=["otbr-cli", "router-table"], action_cost_s=1
    ),
    # meshdiag topology — single command, a few seconds.
    "td-otbr-cli-meshdiag-topology.json": FileAction(
        max_age_s=3600, action=["otbr-cli", "meshdiag", "topology"], action_cost_s=5
    ),
    # Per-router meshdiag commands — ~1–2 s each router; 90 s for ~50-router network.
    "td-otbr-cli-meshdiag-router-childip6.json": FileAction(
        max_age_s=3600, action=["otbr-cli", "meshdiag", "childip6"], action_cost_s=90
    ),
    "td-otbr-cli-meshdiag-router-childtables.json": FileAction(
        max_age_s=3600,
        action=["otbr-cli", "meshdiag", "childtable"],
        action_cost_s=90,  # ~1–2 s per router
    ),
    "td-otbr-cli-meshdiag-router-neighbortables.json": FileAction(
        max_age_s=3600,
        action=["otbr-cli", "meshdiag", "routerneighbortable"],
        action_cost_s=90,  # ~1–2 s per router
    ),
    # networkdiag — TLV request per router with retries; up to ~8 min on large networks.
    "td-otbr-cli-networkdiag-topology.json": FileAction(
        max_age_s=3600,
        action=["otbr-cli", "networkdiag", "topology"],
        action_cost_s=480,  # ~8 min for ~60 routers with timeout retries
    ),
    # REST API downloads — single HTTP call, near-instant.
    "td-otbr-restapi-dataset-active.json": FileAction(
        max_age_s=3600, action=["otbr-restapi", "download"], action_cost_s=1
    ),
    "td-otbr-restapi-devices.json": FileAction(
        max_age_s=3600, action=["otbr-restapi", "download"], action_cost_s=1
    ),
    "td-otbr-restapi-diagnostics.json": FileAction(
        max_age_s=3600, action=["otbr-restapi", "download"], action_cost_s=1
    ),
    # Eve topology exports — externally managed static files.
    "example-small-Eve Thread Network Layout.evethreadlayout": FileAction(
        max_age_s=3600, action="STATIC", action_cost_s=1
    ),
    "Eve Thread Network Layout.evethreadlayout": FileAction(
        max_age_s=3600, action="STATIC", action_cost_s=1
    ),
    "td-eve-topology.json": FileAction(
        max_age_s=3600, action="STATIC", action_cost_s=1
    ),
    # Pre-merged output — produced by dataset_merge; treated as static here.
    "td-merged-topology-all.json": FileAction(
        max_age_s=3600, action="STATIC", action_cost_s=1
    ),
}


def get_file_action(filename: str) -> FileAction | None:
    """Case-insensitive lookup in FILE_ACTION_MAP.

    Returns the matching FileAction, or None if the filename is unknown.
    """
    lower = filename.lower()
    for key, action in FILE_ACTION_MAP.items():
        if key.lower() == lower:
            return action
    return None


def is_file_fresh(file_path: Path, max_age_s: int) -> bool:
    """Return True if *file_path* exists and its mtime is within *max_age_s* seconds."""
    try:
        mtime = file_path.stat().st_mtime
    except FileNotFoundError:
        return False
    return (time.time() - mtime) < max_age_s


def parse_request_cache_control(header_value: str | None) -> dict:
    """Parse a Cache-Control request header string into a dict.

    Examples::

        parse_request_cache_control("no-cache")
        # -> {"no-cache": True}

        parse_request_cache_control("max-age=600, no-store")
        # -> {"max-age": 600, "no-store": True}

        parse_request_cache_control(None)
        # -> {}
    """
    if not header_value:
        return {}
    result: dict = {}
    for directive in header_value.split(","):
        directive = directive.strip()
        if "=" in directive:
            name, _, value = directive.partition("=")
            name = name.strip().lower()
            value = value.strip()
            try:
                result[name] = int(value)
            except ValueError:
                result[name] = value
        else:
            result[directive.lower()] = True
    return result


def build_cache_response_headers(max_age_s: int) -> dict[str, str]:
    """Return HTTP response headers for cache control.

    Returns a dict with ``Cache-Control`` and ``Last-Modified`` headers.
    ``Last-Modified`` is set to the current time (UTC) in RFC 2822 format.
    """
    last_modified = email.utils.formatdate(time.time(), usegmt=True)
    return {
        "Cache-Control": f"max-age={max_age_s}",
        "Last-Modified": last_modified,
    }


# ---------------------------------------------------------------------------
# End Phase 1
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Phase 2 — aiohttp async server
# ---------------------------------------------------------------------------

# Ensure .mjs and other types are served with the right Content-Type on
# minimal container images where the OS mime database may be absent.
mimetypes.add_type("application/javascript", ".js")
mimetypes.add_type("application/javascript", ".mjs")
mimetypes.add_type("application/json", ".json")
mimetypes.add_type("text/css", ".css")
mimetypes.add_type("text/html", ".html")

# Keyed by filename; value is an asyncio.Task running run_td_cli for that file.
# Prevents duplicate concurrent subprocess invocations for the same file.
_active_processes: dict[str, "asyncio.Task[int]"] = {}

# Phase 4 — async job tracking (DD-2 Option B)
_LONG_COST_THRESHOLD_S = 300  # actions with cost > this get 202 + polling


@dataclasses.dataclass
class JobStatus:
    job_id: str
    filename: str
    status: str  # "running" | "done" | "error"
    detail: str = ""


# Registry of in-flight and recently-completed jobs.
_job_registry: dict[str, JobStatus] = {}


def _safe_filename(filename: str) -> bool:
    """Return True if *filename* contains no path-traversal characters."""
    return (
        bool(filename)
        and "/" not in filename
        and "\\" not in filename
        and ".." not in filename
        and "\x00" not in filename
    )


async def run_td_cli(action_args: list[str], data_dir: Path) -> int:
    """Invoke td_cli.py as a subprocess and return its exit code."""
    td_cli_path = Path(__file__).parent / "td_cli.py"  # DD-5
    # logging.debug("Running td_cli with args: %s", " ".join(action_args))
    logging.debug("Spawning subprocess: %s %s", sys.executable, td_cli_path)
    process = await asyncio.create_subprocess_exec(
        sys.executable,
        str(td_cli_path),
        *action_args,
        "--datadir", str(data_dir),  # DD-6
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await process.communicate()
    if stdout:
        logging.info("td_cli stdout: %s", stdout.decode(errors="replace"))
    if stderr:
        logging.warning("td_cli stderr: %s", stderr.decode(errors="replace"))
    return process.returncode  # type: ignore[return-value]


async def handle_data_api(request: aiohttp.web.Request) -> aiohttp.web.Response:
    """GET /api/data/{filename} — serve or generate a data file."""
    # logging.debug("Received request for %s", request.path)
    filename = request.match_info["filename"]

    # 2a. Reject path traversal.
    if not _safe_filename(filename):
        raise aiohttp.web.HTTPNotFound()

    # 2b. Look up FileAction.
    file_action = get_file_action(filename)
    if file_action is None:
        raise aiohttp.web.HTTPNotFound(reason=f"Unknown filename: {filename}")

    # 2c. Parse Cache-Control request header.
    cc = parse_request_cache_control(request.headers.get("Cache-Control"))
    no_cache = bool(cc.get("no-cache", False))

    # 2d. Resolve full file path.
    data_dir: Path = request.app["td_data_dir"]
    file_path = data_dir / filename

    # 2e/2f. Determine whether to regenerate.
    is_static = file_action.action == "STATIC"
    file_exists = file_path.is_file()

    if is_static:
        # STATIC files are managed externally; never regenerated.
        if not file_exists:
            raise aiohttp.web.HTTPNotFound(
                reason=f"Static file not found: {filename}")
    else:
        needs_regen = (
            not file_exists
            or no_cache
            or not is_file_fresh(file_path, file_action.max_age_s)
        )
        if needs_regen:
            # 2g / 4.1: Run td_cli; deduplicate concurrent requests for the same file.
            # type: ignore[assignment]
            action_args: list[str] = file_action.action

            # Phase 4 (task 4.1): long-cost actions get 202 + polling job API.
            if file_action.action_cost_s > _LONG_COST_THRESHOLD_S:
                # Re-use an existing job for the same filename if already running.
                existing_job = next(
                    (
                        j for j in _job_registry.values()
                        if j.filename == filename and j.status == "running"
                    ),
                    None,
                )
                if existing_job is not None:
                    job_id = existing_job.job_id
                else:
                    job_id = str(uuid.uuid4())
                    job = JobStatus(
                        job_id=job_id, filename=filename, status="running"
                    )
                    _job_registry[job_id] = job

                    async def _run_job(
                        jid: str = job_id,
                        args: list[str] = action_args,
                        ddir: Path = data_dir,
                    ) -> None:
                        exit_code = await run_td_cli(args, ddir)
                        j = _job_registry.get(jid)
                        if j is None:
                            return
                        if exit_code == 0:
                            j.status = "done"
                        else:
                            j.status = "error"
                            j.detail = f"td_cli exit code {exit_code}"

                    asyncio.ensure_future(_run_job())

                body = json.dumps(
                    {
                        "job_id": job_id,
                        "status": "running",
                        "filename": filename,
                    }
                )
                return aiohttp.web.Response(
                    status=202,
                    content_type="application/json",
                    text=body,
                    headers={
                        "Location": f"/api/job/{job_id}",
                        "Access-Control-Allow-Origin": "*",
                    },
                )

            # Short-cost action: run synchronously (original Phase 2 path).
            if filename in _active_processes:
                logging.info("Awaiting existing td_cli task for %s", filename)
                try:
                    await _active_processes[filename]
                except Exception:
                    # Error handling is done by the originating coroutine.
                    pass
                if not file_path.is_file():
                    raise aiohttp.web.HTTPBadGateway(
                        reason=f"td_cli failed for {filename}"
                    )
            else:
                task: asyncio.Task[int] = asyncio.ensure_future(
                    run_td_cli(action_args, data_dir)
                )
                _active_processes[filename] = task
                try:
                    exit_code = await task
                finally:
                    _active_processes.pop(filename, None)
                if exit_code != 0:
                    raise aiohttp.web.HTTPBadGateway(
                        reason=f"td_cli failed for {filename} (exit {exit_code})"
                    )

    # 2h. Read file from data_dir.
    try:
        payload = file_path.read_bytes()
    except OSError as exc:
        logging.error("Failed to read %s: %s", file_path, exc)
        raise aiohttp.web.HTTPInternalServerError()

    # 2i. Send response with cache and CORS headers.
    cache_headers = build_cache_response_headers(file_action.max_age_s)
    suffix = file_path.suffix.lower()
    content_type = "application/json" if suffix == ".json" else "application/octet-stream"

    return aiohttp.web.Response(
        body=payload,
        content_type=content_type,
        headers={
            **cache_headers,
            "Access-Control-Allow-Origin": "*",  # 2.6 CORS
        },
    )


async def handle_job_api(request: aiohttp.web.Request) -> aiohttp.web.Response:
    """GET /api/job/{job_id} — poll the status of a long-running td_cli job."""
    job_id = request.match_info["job_id"]
    job = _job_registry.get(job_id)
    if job is None:
        raise aiohttp.web.HTTPNotFound(reason=f"Unknown job: {job_id}")

    if job.status == "running":
        body = {"status": "running"}
    elif job.status == "done":
        body = {"status": "done", "filename": job.filename}
    else:
        body = {"status": "error", "detail": job.detail}

    return aiohttp.web.Response(
        content_type="application/json",
        text=json.dumps(body),
        headers={"Access-Control-Allow-Origin": "*"},
    )


async def handle_root(request: aiohttp.web.Request) -> aiohttp.web.Response:
    """Redirect / to /tdash.html."""
    raise aiohttp.web.HTTPFound("/tdash.html")


# ---------------------------------------------------------------------------
# End Phase 2
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Start the Thread Network Topology Dashboard web server.",
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true", help="Enable verbose (INFO) logging"
    )
    parser.add_argument(
        "--debug", "-d", action="store_true", help="Enable debug logging"
    )
    parser.add_argument(
        "--host",
        default=os.environ.get("HOST", TD_WEB_HOST_ADDR),
        help=f"Host/address to bind to (default: '{TD_WEB_HOST_ADDR}', env: HOST)",
    )
    parser.add_argument("--datadir", default=None, help=TD_DATA_DIR_ARG_HELP)
    parser.add_argument(
        "--port",
        type=int,
        default=int(os.environ.get("PORT", TD_WEB_HOST_PORT)),
        help=f"Port to listen on (default: {TD_WEB_HOST_PORT}, env: PORT)",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    logging.basicConfig(
        level=logging.INFO, format="[%(asctime)s] %(levelname)s: %(message)s"
    )

    parser = build_parser()
    args = parser.parse_args(argv)

    # Apply verbosity / debug flags
    if args.debug:
        logging.getLogger().setLevel(logging.DEBUG)
    elif args.verbose:
        logging.getLogger().setLevel(logging.INFO)

    static_root = Path(__file__).resolve().parent
    td_data_dir_resolution = resolve_data_dir_with_source(
        datadir_arg=args.datadir)
    td_data_dir = td_data_dir_resolution.path

    logging.info(format_data_dir_log_message(td_data_dir_resolution))

    app = aiohttp.web.Application()
    app["td_data_dir"] = td_data_dir

    # Specific routes are registered before the static catch-all.
    app.router.add_get("/", handle_root)
    app.router.add_get("/api/data/{filename}", handle_data_api)
    app.router.add_get("/api/job/{job_id}", handle_job_api)
    # Serve all static assets (HTML, JS, CSS, …) from the src/ directory.
    app.router.add_static(
        "/", static_root, show_index=False, follow_symlinks=False)

    logging.info("Starting tdash webserver dashboard (aiohttp)...")
    logging.info(
        "Serving at http://%s:%s (/ redirects to /tdash.html)",
        args.host or "localhost",
        args.port,
    )
    logging.info("Static assets root: %s", static_root)
    logging.info("Data root: %s", td_data_dir)

    aiohttp.web.run_app(
        app,
        host=args.host if args.host else None,
        port=args.port,
        access_log=logging.getLogger("aiohttp.access"),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
